### ISSUE TITLE
Unable to use "jsduck" goal

### ISSUE THREAD

**Issue by brdegenars** [pguedes/maven-jsduck#7]
Are the goals of any given build phase limited to "clean-jsduck" only? I seem to get an RKelly::SyntaxError every time I attempt to execute a "jsduck" goal from my POM plugin definition from within the defined execution. "clean-jsduck" works without issue every time. 

PARTIAL STACK TRACE FROM MY CONSOLE: 

[ERROR] Failed to execute goal nl.secondfloor.mojo.jsduck:jsduck-maven-plugin:0.
2.1-SNAPSHOT:jsduck (install-duck) on project dashboard: Execution install-duck
of goal nl.secondfloor.mojo.jsduck:jsduck-maven-plugin:0.2.1-SNAPSHOT:jsduck fai
led: (SyntaxError) RKelly::SyntaxError -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal n
l.secondfloor.mojo.jsduck:jsduck-maven-plugin:0.2.1-SNAPSHOT:jsduck (install-duc
k) on project dashboard: Execution install-duck of goal nl.secondfloor.mojo.jsdu
ck:jsduck-maven-plugin:0.2.1-SNAPSHOT:jsduck failed: (SyntaxError) RKelly::Synta
xError
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBu
ild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution install-d
uck of goal nl.secondfloor.mojo.jsduck:jsduck-maven-plugin:0.2.1-SNAPSHOT:jsduck
 failed: (SyntaxError) RKelly::SyntaxError
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:110)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:209)
        ... 19 more
Caused by: org.jruby.embed.EvalFailedException: (SyntaxError) RKelly::SyntaxErro
r
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java
:132)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:12
63)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.ja
va:1256)
        at nl.secondfloor.mojo.jsduck.JsDuckMojo.runJsDuck(JsDuckMojo.java:315)
        at nl.secondfloor.mojo.jsduck.JsDuckMojo.execute(JsDuckMojo.java:150)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:101)
        ... 20 more
Caused by: org.jruby.exceptions.RaiseException: (SyntaxError) RKelly::SyntaxErro
r

**Comment by sergiofilhowz** [comment]
the same problem is happening to me
